export type BuildprintCategory = 'Framework / Architecture' | 'Product OS' | 'Feature / Extension' | 'Workflow OS' | 'Mapped Project';
export type BuildprintTier = 'basic' | 'strong' | 'agent-grade';
export type BuildprintStatus = 'publishable-draft' | 'dry-run-needed' | 'validated';

export type BuildprintFile = { path: string; purpose: string; required: boolean };
export type BuildprintTrustBadge = { label: string; detail: string; tone?: 'success' | 'info' | 'warning' };
export type Buildprint = {
  slug: string;
  title: string;
  creator: string;
  category: BuildprintCategory;
  tier: BuildprintTier;
  status: BuildprintStatus;
  runtime: string[];
  stack: string[];
  iconKeys?: string[];
  difficulty: 'Medium' | 'Advanced';
  summary: string;
  promise: string;
  includes: string[];
  risks: string[];
  files: BuildprintFile[];
  checks: string[];
  trustBadges?: BuildprintTrustBadge[];
  plainDescription?: string;
  whatYouGet?: string[];
  whatYouNeed?: string[];
  architectureFlow?: string[];
  copyPrompt: string;
  githubUrl: string;
  originGithubUrl?: string;
  originLabel?: string;
  rawBaseUrl: string;
  featured?: boolean;
};

export function implementationEstimate(bp: Pick<Buildprint, 'tier' | 'category' | 'difficulty' | 'files' | 'checks'>) {
  let minutes = bp.tier === 'basic' ? 15 : bp.tier === 'strong' ? 25 : 35;
  if (bp.category === 'Product OS' || bp.category === 'Mapped Project') minutes += 5;
  if (bp.category === 'Workflow OS') minutes += 5;
  if (bp.category === 'Feature / Extension') minutes -= 5;
  if (bp.difficulty === 'Advanced') minutes += 5;
  const low = Math.max(15, Math.round((minutes - 10) / 15) * 15);
  const high = Math.max(30, Math.round((minutes + 10) / 15) * 15);
  return `${low}–${high} min`;
}

export const repoUrl = 'https://github.com/DomEscobar/agent-buildprint';
// Production DNS for agent-buildprint.com is not yet serving this static site.
// Keep generated manifests/CLI bootstrap commands on the live preview origin until DNS is cut over.
export const siteBase = import.meta.env.PUBLIC_SITE_BASE || 'https://agent-buildprint.com';

export const canonicalFilePurposes: Record<string, string> = {
  'BUILDPRINT.md': 'architecture truth / coding-agent contract',
  'SPEC.md': 'behavior truth / requirements',
  'PLAN.md': 'execution index',
  'plans/*.md': 'tiny phase task rails',
  'CONTRACTS.md': 'interfaces and data contracts',
  'DEFAULT_PRESET.md': 'configurable defaults, no fixed identity',
  'TEST_MATRIX.md': 'risk-to-test alignment',
  'VALIDATION_TEMPLATE.md': 'completion report template',
  'questions.md': 'configuration interview',
};

const rawFor = (slug: string) => `${siteBase}/buildprints/${slug}/files`;
const localPrompt = (slug: string, title: string) => `Use the ${title} Buildprint. First bootstrap exact snapshots: agb start ${siteBase}/buildprints/${slug}/package.json . If agb is not installed, clone https://github.com/DomEscobar/agent-buildprint and run node agent-buildprint/bin/agb.js start ${siteBase}/buildprints/${slug}/package.json . Then read .buildprint/next-agent.md and continue. Do not write Buildprint snapshots manually.`;
const agentTrustBadges: BuildprintTrustBadge[] = [
  { label: 'Snapshot bootstrap passed', detail: 'agb start downloaded exact Markdown snapshots; HTML/parked-domain responses are rejected.', tone: 'success' },
  { label: 'Codex dry-run passed', detail: 'A fresh Codex run built a fixture-safe implementation from the Buildprint package.', tone: 'success' },
  { label: 'Tests pass', detail: 'Dry-run implementation completed its local tests/static checks without real credentials.', tone: 'success' },
  { label: 'Gated publishing', detail: 'Publishing is manual/mock/approval-gated by default, never raw auto-publish.', tone: 'info' },
];

export const buildprints: Buildprint[] = [
  {
    slug: 'ai-influencer-os',
    title: 'AI Influencer OS',
    creator: 'Agent Buildprint',
    category: 'Product OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['OpenClaw'],
    stack: ['OpenClaw', 'Persona memory', 'Wavespeed', 'Social publishing', 'Docker'],
    iconKeys: ['openclaw', 'json', 'docker'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'OpenClaw AI creator system with configurable persona, memory, life continuity, Wavespeed images, social drafts, QA, and publishing handoff.',
    plainDescription: 'A blueprint for building an AI creator/influencer system with persona memory, image generation, content planning, draft queues, QA, and controlled publishing handoff.',
    whatYouGet: ['AI creator/influencer operating system', 'Configurable persona and memory model', 'Image generation workflow', 'Social draft and media queue', 'Approval-gated publishing handoff', 'Manager audit and safety checks'],
    whatYouNeed: ['Nothing for local/mock mode', 'Image provider key, such as Wavespeed, for real image generation', 'Social account/browser access if you want real publishing', 'Brand/persona decisions and media policy from the human'],
    architectureFlow: ['Persona', 'Ideas', 'Images', 'Drafts', 'Approval', 'Publish'],
    promise: 'An agent-grade Buildprint package for a full AI influencer system. The architecture is fixed; persona, voice, channels, content lanes, and approval policy stay configurable.',
    includes: ['OpenClaw runtime shape', 'Configurable persona preset', 'Relationship memory', 'Life state and journal', 'Wavespeed image skill', 'Social drafts and media queue', 'Manager audit', 'Browser/noVNC publishing handoff'],
    risks: ['Generic chatbot drift', 'Fixed persona/name leakage', 'Ungrounded public claims', 'Unsafe media requests', 'Image provider drift', 'Auto-publishing by default'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'plans/00-alignment.md', purpose: 'phase 00 alignment rail', required: true },
      { path: 'plans/01-openclaw-runtime-shape.md', purpose: 'phase 01 OpenClaw runtime shape rail', required: true },
      { path: 'plans/02-persona-runtime.md', purpose: 'phase 02 persona runtime rail', required: true },
      { path: 'plans/03-memory-life-state.md', purpose: 'phase 03 memory/life rail', required: true },
      { path: 'plans/04-wavespeed-image.md', purpose: 'phase 04 Wavespeed image rail', required: true },
      { path: 'plans/05-social-planner.md', purpose: 'phase 05 social planner rail', required: true },
      { path: 'plans/06-publisher-handoff.md', purpose: 'phase 06 publisher handoff rail', required: true },
      { path: 'plans/07-manager-audit.md', purpose: 'phase 07 manager audit rail', required: true },
      { path: 'plans/08-tests-validation.md', purpose: 'phase 08 tests and validation rail', required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'DEFAULT_PRESET.md', purpose: canonicalFilePurposes['DEFAULT_PRESET.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'VALIDATION_TEMPLATE.md', purpose: canonicalFilePurposes['VALIDATION_TEMPLATE.md'], required: true },
      { path: 'questions.md', purpose: canonicalFilePurposes['questions.md'], required: true },
    ],
    checks: ['OpenClaw runtime command/blocker exists', 'LLM analyzer adapter prevents keyword-only drift', 'Wavespeed real adapter shape exists', 'Tests use mock image mode without external APIs', 'User memory and self-state are separate', 'noVNC handoff service shape exists', 'Publishing is mock/manual-gated by default'],
    trustBadges: agentTrustBadges,
    githubUrl: `${repoUrl}/tree/main/buildprints/ai-influencer-os`,
    rawBaseUrl: rawFor('ai-influencer-os'),
    copyPrompt: `${localPrompt('ai-influencer-os', 'AI Influencer OS')} Do not auto-publish by default.`,
  },
  {
    slug: 'automated-ai-blog-os',
    title: 'Automated AI Blog OS',
    creator: 'Agent Buildprint',
    category: 'Product OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Astro/MDX'],
    stack: ['Astro/MDX', 'Research scanner', 'Idea scoring', 'SEO checks', 'Approval queue'],
    iconKeys: ['astro', 'md', 'json'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Approval-gated AI blog publishing system that researches topics, scores ideas, drafts visual posts, validates SEO/build output, and publishes only through configured gates.',
    plainDescription: 'A blueprint for an automated blog workflow that finds ideas, drafts posts, validates claims and SEO, then waits for approval before publishing.',
    whatYouGet: ['AI-assisted blog publishing workflow', 'Source scanning and idea scoring', 'Draft generation with claim/source tracking', 'SEO, metadata, sitemap, RSS, and llms.txt checks', 'Approval queue before publishing', 'Manager audit for stale or weak drafts'],
    whatYouNeed: ['Nothing for local/mock mode', 'AI provider key for real drafting/research assistance', 'Website/repo access for real publishing', 'Human approval policy and editorial taste'],
    architectureFlow: ['Sources', 'Ideas', 'Drafts', 'SEO checks', 'Approval', 'Publish'],
    promise: 'An agent-grade Buildprint package for automated AI blogging: source scanning, idea scoring, content memory, draft generation, visual plans, claim grounding, SEO validation, approval queue, and gated publishing/scheduling.',
    includes: ['Source scanner', 'Rubric-based idea scoring', 'Content memory', 'Draft generator with source/claim maps', 'Visual post templates', 'Claim grounding validator', 'SEO/build/feed validator', 'Approval queue', 'Gated publisher/scheduler', 'Manager audit'],
    risks: ['Generic SEO filler', 'Unsourced claims', 'Source laundering', 'Repeated content angles', 'Fake expertise', 'Broken metadata/RSS/sitemap/llms outputs', 'Publishing without approval', 'External API calls in tests'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'plans/00-alignment.md', purpose: 'phase 00 alignment rail', required: true },
      { path: 'plans/01-content-skeleton.md', purpose: 'phase 01 content skeleton rail', required: true },
      { path: 'plans/02-source-scanner.md', purpose: 'phase 02 source scanner rail', required: true },
      { path: 'plans/03-idea-scoring.md', purpose: 'phase 03 idea scoring rail', required: true },
      { path: 'plans/04-drafting-visuals.md', purpose: 'phase 04 drafting and visuals rail', required: true },
      { path: 'plans/05-seo-claim-validation.md', purpose: 'phase 05 SEO and claim validation rail', required: true },
      { path: 'plans/06-approval-publishing.md', purpose: 'phase 06 approval and publishing rail', required: true },
      { path: 'plans/07-manager-audit.md', purpose: 'phase 07 manager audit rail', required: true },
      { path: 'plans/08-tests-validation.md', purpose: 'phase 08 tests and validation rail', required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'DEFAULT_PRESET.md', purpose: canonicalFilePurposes['DEFAULT_PRESET.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'VALIDATION_TEMPLATE.md', purpose: canonicalFilePurposes['VALIDATION_TEMPLATE.md'], required: true },
      { path: 'questions.md', purpose: canonicalFilePurposes['questions.md'], required: true },
      { path: 'checks/acceptance.md', purpose: 'acceptance checklist', required: true },
      { path: 'policies/publishing.md', purpose: 'publishing safety policy', required: true },
      { path: 'schemas/buildprint.meta.json', purpose: 'package metadata schema example', required: false },
    ],
    checks: ['Sources are captured as records, not invented', 'Ideas use explicit scoring rubric', 'Drafts include source map and claim map', 'Ungrounded factual claims block publishing', 'SEO metadata, structured data, sitemap/RSS/llms, and build are validated', 'Unapproved drafts cannot publish by default', 'Tests run without real network/publishing credentials', 'Manager audit reports stale/weak/blocked items'],
    trustBadges: agentTrustBadges,
    githubUrl: `${repoUrl}/tree/main/buildprints/automated-ai-blog-os`,
    rawBaseUrl: rawFor('automated-ai-blog-os'),
    copyPrompt: `${localPrompt('automated-ai-blog-os', 'Automated AI Blog OS')} Build the approval-gated AI blog pipeline with source scanning, idea scoring, draft generation, claim/SEO validation, approval queue, gated publishing/scheduling, manager audit, and tests. Do not auto-publish by default.`,
  },
  {
    slug: 'portable-novel-storyboard-pipeline',
    title: 'Portable Novel-to-Storyboard Pipeline',
    creator: 'Agent Buildprint',
    category: 'Mapped Project',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['React/Vite target', 'Mock-first AI providers', 'Browser QA'],
    stack: ['Novel import', 'Event extraction', 'ScriptAgent workflow', 'ProductionAgent storyboard', 'Preview manifest export'],
    iconKeys: ['typescript', 'json', 'md'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Clean-room, Toonflow-inspired portable creative pipeline that maps novel chapters into events, staged scripts, storyboard rows, assets, jobs, and a preview/export manifest.',
    plainDescription: 'A blueprint for a novel-to-storyboard webapp: import chapters, extract story events, generate staged scripts, create storyboard rows, queue mock media jobs, and export a preview manifest.',
    whatYouGet: ['Novel-to-storyboard webapp workflow', 'Chapter import and event extraction', 'ScriptAgent-style script workspace', 'ProductionAgent-style storyboard rows', 'Mock image/video generation tasks', 'Preview/export manifest'],
    whatYouNeed: ['Nothing for local/mock mode', 'AI provider key for real script/event generation', 'Image/video provider keys for live media generation', 'Source text/story rights and creative direction from the human'],
    architectureFlow: ['Chapters', 'Events', 'Scripts', 'Storyboard', 'Media jobs', 'Preview'],
    promise: 'A validated mapped-project Buildprint for rebuilding the portable novel-to-storyboard workflow without copying Toonflow source or claiming full clone/media-export parity.',
    includes: ['Portable workflow scope', 'Webapp target spec', 'ScriptAgent and ProductionAgent contracts', 'XML output contract and repair loop', 'Async job/cancellation model', 'Mock-first provider adapters', 'UI/workbench mapping with confidence labels', 'Preview composition manifest', 'Head-to-foot QA gate', 'Browser QA scenarios', 'Parity claims and explicit non-claims', 'Machine-readable phase/acceptance/claim gates'],
    risks: ['Accidentally implying full Toonflow parity', 'Provider API drift', 'Media export overclaiming', 'Canvas/workbench exactness overclaiming', 'Live provider costs without env gates', 'Persistence mode confusion'],
    files: [
      { path: 'BUILDPRINT.md', purpose: 'canonical start, authority spine, binding slice, phase gates, and acceptance gates', required: true },
      { path: 'README.md', purpose: 'package overview and scope boundary', required: true },
      { path: 'buildprint.json', purpose: 'machine-readable authority, file roles, binding slice, and forbidden defaults', required: true },
      { path: 'phases.yaml', purpose: 'structured phase gates for agent alignment and proof before proceeding', required: true },
      { path: 'acceptance.yaml', purpose: 'structured done criteria for tests, browser QA, artifacts, and no-network gates', required: true },
      { path: 'claims.yaml', purpose: 'safe/unsafe claim contract and required/forbidden wording', required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'WEBAPP_TARGET_SPEC.md', purpose: 'React/Vite target architecture, routes, pages, and state flows', required: true },
      { path: 'UI_CANVAS_MAP.md', purpose: 'UI/workbench and canvas behavior mapping with confidence levels', required: true },
      { path: 'PROVIDER_ADAPTERS.md', purpose: 'mock-first text/image/video provider contracts and optional live-provider gates', required: true },
      { path: 'XML_OUTPUT_CONTRACT.md', purpose: 'ScriptAgent XML tags, parsing, validation, and repair loop', required: true },
      { path: 'ASYNC_JOB_MODEL.md', purpose: 'job/task lifecycle, retry, cancellation, idempotency, and persistence model', required: true },
      { path: 'PREVIEW_COMPOSITION_SPEC.md', purpose: 'PortablePreviewManifest and preview/export package contract', required: true },
      { path: 'AGENT_PROMPT_PACK.md', purpose: 'compressed prompt contracts for ScriptAgent and ProductionAgent', required: true },
      { path: 'HEAD_TO_FOOT_QA.md', purpose: 'canonical end-to-end acceptance gate for generated webapp proofs', required: true },
      { path: 'BROWSER_QA_SCENARIOS.md', purpose: 'browser/runtime scenarios and negative paths', required: true },
      { path: 'PARITY_CLAIMS.md', purpose: 'safe claims, non-claims, and evidence needed to upgrade parity', required: true },
      { path: 'TRACEABILITY_MATRIX.md', purpose: 'source evidence to requirement/check traceability', required: true },
      { path: 'SYSTEM_MAP.md', purpose: 'mapped system zones and portable pipeline boundaries', required: false },
      { path: 'THREAT_MODEL.md', purpose: 'security and abuse-case model', required: false },
      { path: 'OBSERVABILITY.md', purpose: 'logs, metrics, traces, and runbook expectations', required: false },
      { path: 'AGENT_HANDOFF.md', purpose: 'agent implementation handoff notes', required: false },
      { path: 'LLM_FLOW.md', purpose: 'LLM orchestration and agent flow notes', required: false },
      { path: 'PORTABILITY.md', purpose: 'portability and clean-room constraints', required: false },
      { path: 'IMPLEMENTATION_ROADMAP.md', purpose: 'implementation roadmap', required: false },
    ],
    checks: ['Selected fidelity target is workflow-proof + contract/runtime proof, not full clone parity', 'Buildprint uses clean-room artifacts only; original app source is not implementation input', 'Mock/no-network providers are default', 'Browser UI proofs require real runtime clicks, rendered-state parsing, screenshots, and runtime report', 'Provider/live smoke is env-gated and optional', 'Export claim is PortablePreviewManifest/preview package only, not final stitched-video parity', 'PARITY_CLAIMS.md and claims.yaml label safe claims, non-claims, and upgrade evidence'],
    trustBadges: [
      { label: 'Clean-room mapped project', detail: 'Published as a portable workflow Buildprint; not a Toonflow clone or source copy.', tone: 'success' },
      { label: 'Runtime proof validated', detail: 'The generated proof was build/test/runtime checked with real browser interactions.', tone: 'success' },
      { label: 'Mock-first providers', detail: 'Default behavior avoids live API calls; live provider smoke is optional and env-gated.', tone: 'info' },
      { label: 'Explicit parity boundary', detail: 'Claims stop at workflow/contract/runtime proof and preview manifest export unless upgraded with evidence.', tone: 'warning' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/portable-novel-storyboard-pipeline`,
    originGithubUrl: 'https://github.com/HBAI-Ltd/Toonflow-app',
    originLabel: 'HBAI-Ltd/Toonflow-app',
    rawBaseUrl: rawFor('portable-novel-storyboard-pipeline'),
    copyPrompt: `${localPrompt('portable-novel-storyboard-pipeline', 'Portable Novel-to-Storyboard Pipeline')} Build a clean-room portable webapp proof for the novel-to-storyboard workflow. Use mock/no-network providers by default. Produce a PortablePreviewManifest/preview package only; do not claim Toonflow clone, provider parity, exact workbench parity, or final stitched-video export parity unless explicitly upgraded with evidence.`,
  },
  {
    slug: 'buildprint-mapper-os',
    title: 'Buildprint Mapper OS',
    creator: 'Agent Buildprint',
    category: 'Workflow OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Codex/Cursor/Claude Code', 'optional agb bootstrap'],
    stack: ['Repository analysis', 'System decomposition', 'Buildprint extraction', 'Submission review'],
    iconKeys: ['md', 'json', 'typescript'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Validated workflow for turning an existing repo into scoped, production-grade selected-scope Buildprints — smaller scope, no fake MVP surfaces.',
    plainDescription: 'A blueprint for turning a repo into useful Buildprints: scan the codebase, find good product/feature slices, choose one, and extract a real implementation plan where included features are complete instead of mocked.',
    whatYouGet: ['Repo-to-Buildprint mapping workflow', 'System map of an existing codebase', 'Scoped product/feature blueprint candidates', 'Production-grade selected-scope contract', 'Agent-first execution brief + XML contract', 'Anti-context-rot current state', 'No-fake implementation checklist', 'One selected Buildprint package', 'Clean-room reversal proof plan', 'Submission/review checklist'],
    whatYouNeed: ['Nothing for public repos', 'GitHub/private repo access if the source is private', 'A human scope choice when multiple candidates exist', 'Permission to use any private source code'],
    architectureFlow: ['Repo', 'System map', 'Candidates', 'Selection', 'Package', 'Proof'],
    promise: 'An official workflow Buildprint for creator submissions: evidence-backed system maps, scoped Buildprint candidates, production-grade selected-scope extraction, reversal validation, no-fake implementation checks, and an honest gap report.',
    includes: ['Safety and secrets boundary', 'Repo census', 'SYSTEM_MAP.md', 'BUILDPRINT_CANDIDATES.md', 'Human scope decision gate', 'Progressive questions.md', 'Clean-room reversal report', 'QA_PLAN.md', 'IMPLEMENTATION_COMPLETENESS.md', 'TRACEABILITY_MATRIX.md', 'Single Buildprint extraction', 'Hierarchical System Buildprint extraction', 'Submission checklist', 'Golden eval targets'],
    risks: ['Whole-repo sludge', 'Secret leakage', 'Hallucinated intent', 'Invented validation results', 'Missing scope', 'Vague marketplace submissions', 'Unclear module boundaries', 'Generic QA plans', 'Missing traceability'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'plans/00-safety-boundaries.md', purpose: 'phase 00 safety and write boundaries', required: true },
      { path: 'plans/01-repo-census.md', purpose: 'phase 01 deterministic repo facts', required: true },
      { path: 'plans/02-system-map.md', purpose: 'phase 02 architecture zones and subsystem boundaries', required: true },
      { path: 'plans/03-candidate-buildprints.md', purpose: 'phase 03 candidate Buildprint discovery', required: true },
      { path: 'plans/04-scope-decision.md', purpose: 'phase 04 human scope selection gate', required: true },
      { path: 'plans/05-single-extraction.md', purpose: 'phase 05 selected module extraction', required: true },
      { path: 'plans/06-system-extraction.md', purpose: 'phase 06 hierarchical system extraction', required: true },
      { path: 'plans/07-validation-submission.md', purpose: 'phase 07 validation and submission checklist', required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'VALIDATION_TEMPLATE.md', purpose: canonicalFilePurposes['VALIDATION_TEMPLATE.md'], required: true },
      { path: 'questions.md', purpose: canonicalFilePurposes['questions.md'], required: true },
      { path: 'README.md', purpose: 'creator-facing mapper overview', required: false },
      { path: 'policies/safety.md', purpose: 'secret and safety policy', required: true },
      { path: 'policies/quality.md', purpose: 'max-quality precision, edge-case, and proof policy', required: true },
      { path: 'policies/questions.md', purpose: 'minimal-preflight and dynamic post-discovery question policy', required: true },
      { path: 'templates/AGENT_EXECUTION_BRIEF.md', purpose: 'first-read coding-agent execution brief', required: true },
      { path: 'templates/agent-contract.xml', purpose: 'strict XML instruction envelope for coding agents', required: true },
      { path: 'templates/CURRENT_STATE.md', purpose: 'anti-context-rot phase handoff file', required: true },
      { path: 'templates/manifest.json', purpose: 'machine-checkable required files, gates, and done criteria', required: true },
      { path: 'templates/AGENT_PROMPTING_STANDARD.md', purpose: 'token-attention and agent execution standard', required: false },
      { path: 'templates/QA_PLAN.md', purpose: 'scope-derived QA journey template', required: true },
      { path: 'templates/IMPLEMENTATION_COMPLETENESS.md', purpose: 'no-fake implementation and production-grade selected-scope contract', required: true },
      { path: 'templates/TRACEABILITY_MATRIX.md', purpose: 'source evidence to requirement/check traceability template', required: true },
      { path: 'templates/CAPABILITY_BASELINE.md', purpose: 'famous-product capability and non-parity boundary template', required: false },
      { path: 'templates/THREAT_MODEL.md', purpose: 'security and abuse-case template', required: false },
      { path: 'templates/DATA_LIFECYCLE.md', purpose: 'data ownership/lifecycle/retention template', required: false },
      { path: 'templates/ARCHITECTURE_VIEWS.md', purpose: 'context/container/component/runtime/deployment views template', required: false },
      { path: 'templates/DECISIONS.md', purpose: 'ADR-style mapping decisions template', required: false },
      { path: 'templates/OBSERVABILITY.md', purpose: 'logs/metrics/traces/runbook template', required: false },
      { path: 'templates/QUALITY_SCORECARD.md', purpose: 'publish-readiness and evidence scorecard template', required: false },
      { path: 'checks/acceptance.md', purpose: 'submission acceptance checks', required: true },
      { path: 'prompts/discover.md', purpose: 'candidate discovery prompt', required: true },
      { path: 'prompts/extract-selected.md', purpose: 'selected Buildprint extraction prompt', required: true },
      { path: 'schemas/candidate.schema.json', purpose: 'candidate record schema', required: false },
    ],
    checks: ['Large repos produce candidates before final package unless full-system mode is selected', 'Generated files contain no secret values', 'Claims are labeled OBSERVED/INFERRED/QUESTION', 'Scope includes included/excluded paths', 'Production-grade selected scope is explicit', 'Agent execution brief/XML contract/current state/manifest exist', 'XML and JSON agent contracts parse', 'Mocks/fixtures are not counted as product implementation', 'Included routes/services/providers/persistence/jobs/exports are real or excluded', 'QA plan is derived from mapped flows', 'Traceability matrix links evidence to requirements and checks', 'Submission checklist reports commands run and known gaps', 'No validation results are invented', 'Golden eval examples include stripe-saas, ai-blog-os, malicious-secrets, admin-dashboard, and large-monorepo'],
    trustBadges: [
      { label: 'Submission workflow', detail: 'Defines the official reviewable path from existing repo to scoped Buildprint package.', tone: 'info' },
      { label: 'Safety-first extraction', detail: 'Requires no app-code changes, no secret copying, and explicit unknowns.', tone: 'success' },
      { label: 'Blueprint-first workflow', detail: 'The mapper works as pure coding-agent instructions; CLI bootstrap is optional, not required.', tone: 'success' },
      { label: 'Traceable QA', detail: 'Requires source evidence → requirement → reversal/QA checks instead of generic demo validation.', tone: 'success' },
      { label: 'No fake MVPs', detail: 'Scope may be small, but included capabilities must be real, wired, persistent where relevant, and QA-tested.', tone: 'warning' },
      { label: 'Dogfood proof passed', detail: 'Mapped Seanium/FeedMe with Codex, extracted a static RSS pipeline Buildprint, and passed reversal checks.', tone: 'success' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/buildprint-mapper-os`,
    rawBaseUrl: rawFor('buildprint-mapper-os'),
    copyPrompt: `${localPrompt('buildprint-mapper-os', 'Buildprint Mapper OS')} Use it to map this repo into SYSTEM_MAP.md and BUILDPRINT_CANDIDATES.md first. Ask me to choose one candidate, then extract only that selected scope into buildprint-submission/. Default to production-grade selected scope: smaller scope is OK, but do not create a lazy MVP, mock services as product behavior, placeholder routes, no-op controls, skeleton adapters, or in-memory-only persistence when durability is claimed. Do not require a CLI, do not copy secrets, and do not flatten the repo into one vague document.`,
  },


  {
    slug: 'superpowers-skill-methodology-harness',
    title: 'Superpowers Skill Methodology Harness',
    creator: 'Agent Buildprint',
    category: 'Workflow OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Claude Code', 'Codex', 'OpenCode', 'Gemini', 'Cursor', 'Copilot CLI'],
    stack: ['Session bootstrap', 'Skill routing', 'TDD', 'Subagents', 'Transcript evals'],
    iconKeys: ['md', 'json', 'typescript'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Validated Superpowers-inspired skill-methodology harness: bootstrap skill use before action, route to process skills, enforce design/planning/TDD, execute via subagents, and validate with transcripts.',
    plainDescription: 'A blueprint for building an actual coding-agent skill setup harness, not a manager: startup bootstrap, skill activation, methodology gates, subagent execution, code review, branch finishing, and transcript tests.',
    whatYouGet: ['Session-start bootstrap contract', 'Skill metadata and routing model', 'Brainstorming-before-code workflow', 'Spec and implementation-plan artifacts', 'TDD hard gate', 'Systematic debugging gate', 'Subagent implementation/review loop', 'Transcript acceptance test matrix'],
    whatYouNeed: ['One target agent runtime to support first', 'A skill loading mechanism or plugin adapter', 'A transcript/eval runner', 'A safe subagent/task interface', 'Human policy for exceptions to TDD/design gates'],
    architectureFlow: ['Bootstrap', 'Skill lookup', 'Design', 'Plan', 'TDD', 'Subagents', 'Review', 'Finish'],
    promise: 'A source-backed Buildprint for reconstructing the architecture and behavior contracts behind obra/superpowers as a portable skill-methodology harness.',
    includes: ['Pinned source trace', 'System map', 'Bootstrap and routing contract', 'Skill library map', 'Canonical workflow', 'Subagent orchestration contract', 'Plan/spec/test contracts', 'Transcript-based test matrix', 'Validation status and next proof plan'],
    risks: ['Confusing skill files with a working harness', 'Skipping bootstrap injection', 'Skills not auto-triggering', 'Implementation before design approval', 'TDD theatre without observed red phase', 'Subagent context pollution', 'Reviewer trusting implementer summaries', 'Overclaiming official Superpowers compatibility'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SOURCE_TRACE.md', purpose: 'pinned obra/superpowers source evidence', required: true },
      { path: 'SYSTEM_MAP.md', purpose: 'skill-methodology harness architecture layers', required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'BOOTSTRAP_AND_ROUTING.md', purpose: 'session bootstrap and skill routing contract', required: true },
      { path: 'SKILL_LIBRARY.md', purpose: 'core skills and hard gates to reproduce', required: true },
      { path: 'WORKFLOW.md', purpose: 'design/plan/TDD/debug/review/finish workflow', required: true },
      { path: 'SUBAGENT_ORCHESTRATION.md', purpose: 'fresh subagent per task and two-stage review model', required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'VALIDATION_REPORT.md', purpose: 'proof validation status and remaining hardening', required: true },
      { path: 'proof/package.json', purpose: 'clean-room proof package scripts', required: false },
      { path: 'proof/src/eval.js', purpose: 'transcript eval runner', required: false },
      { path: 'proof/src/harness.js', purpose: 'neutral methodology harness proof', required: false },
      { path: 'proof/src/run-evals.js', purpose: 'eval CLI entrypoint', required: false },
      { path: 'proof/src/skills.js', purpose: 'machine-readable skill registry proof', required: false },
      { path: 'proof/src/subagents.js', purpose: 'subagent packet and review-loop proof', required: false },
      { path: 'proof/src/transcript.js', purpose: 'transcript event recorder', required: false },
      { path: 'proof/tests/harness.test.js', purpose: '6-subtest Node proof test suite', required: false },
    ],
    checks: ['Pinned Superpowers commit recorded', 'Source trace cites README, skill files, plugin manifests, OpenCode bootstrap, and eval/test docs', 'Buildprint distinguishes manager tooling from methodology harness behavior', 'Bootstrap/skill activation is treated as required runtime behavior', 'Acceptance prompt requires brainstorming before code', 'Clean-room proof passes npm test 6/6 and transcript evals 5/5'],
    trustBadges: [
      { label: 'Source-backed mapping', detail: 'Mapped from obra/superpowers at commit f2cbfbefebbfef77321e4c9abc9e949826bea9d7.', tone: 'success' },
      { label: 'Actual skill harness', detail: 'Focuses on bootstrap, activation, methodology gates, subagents, and transcripts—not dashboards or managers.', tone: 'info' },
      { label: 'Clean-room proof passed', detail: 'Codex built a neutral Node.js proof from snapshots; npm test passed 6/6 and transcript evals passed 5/5.', tone: 'success' },
      { label: 'Scoped validation', detail: 'Validated as an inspired/adaptive methodology harness proof, not a production runtime adapter or official clone.', tone: 'warning' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/superpowers-skill-methodology-harness`,
    originGithubUrl: 'https://github.com/obra/superpowers',
    originLabel: 'obra/superpowers',
    rawBaseUrl: rawFor('superpowers-skill-methodology-harness'),
    copyPrompt: `${localPrompt('superpowers-skill-methodology-harness', 'Superpowers Skill Methodology Harness')} Build a clean-room skill-methodology harness proof. Do not make a dashboard/manager. Implement session bootstrap, skill lookup before action, brainstorming-before-code, TDD gate, subagent/review loop contracts, and transcript evals. Keep claims Superpowers-inspired unless installing the official plugin.`,
  },


  {
    slug: 'complete-agent-skills-evaluation-os',
    title: 'Complete Agent Skills Evaluation OS',
    creator: 'Agent Buildprint',
    category: 'Workflow OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Any coding agent', 'JavaScript proof', 'CI-ready adapters'],
    stack: ['Static lint', 'Loadout inventory', 'Skill tests', 'Activation evals', 'Transcript checks', 'Multi-agent safety'],
    iconKeys: ['json', 'md', 'typescript'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Complete evaluation stack for agent skill setups: validate config, measure loadout cost, test skills, check activation, enforce transcript process, and score multi-agent safety.',
    plainDescription: 'A blueprint for evaluating an entire coding-agent setup, not just one skill: installed skills, agents, commands, hooks, MCP, routers, subagents, workflow discipline, token cost, safety, and CI evidence.',
    whatYouGet: ['Setup snapshot and install parity model', 'Static lint gates for agent config files', 'Loadout and token-cost inventory', 'Skill unit/regression test harness pattern', 'Activation and routing eval pattern', 'Transcript/process invariant checks', 'E2E task benchmark model', 'Multi-agent/subagent safety gates', 'Weighted scorecard and CI report contract'],
    whatYouNeed: ['A target agent setup to evaluate', 'Offline fixture cases for deterministic mode', 'Optional live agent/provider credentials for live adapters', 'A safety policy for external/destructive actions', 'A list of critical workflow invariants'],
    architectureFlow: ['Snapshot', 'Lint', 'Inventory', 'Skill tests', 'Activation', 'Transcript', 'Scorecard'],
    promise: 'A validated Buildprint for evaluating complete agent+skills installations from static validity through real behavior, with skill-eval-runner as the core module but not the whole system.',
    includes: ['Deep tool comparison', 'Static lint layer', 'Loadout inventory layer', 'Skill unit eval layer', 'Activation eval layer', 'Transcript process eval layer', 'E2E task bench', 'Multi-agent safety layer', 'Safety policy', 'Weighted scorecard', 'Offline JavaScript proof'],
    risks: ['Mistaking per-skill tests for full setup proof', 'Ignoring activation failures', 'Skipping transcript/order evidence', 'Measuring a drifted install', 'Token bloat from unused loadout', 'Unsafe external actions in live tests', 'Subagent file ownership collisions'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'STATIC_LINT.md', purpose: 'static validation for SKILL/AGENTS/CLAUDE/hooks/MCP/plugin files', required: true },
      { path: 'LOADOUT_INVENTORY.md', purpose: 'token/context footprint and dormant artifact diagnostics', required: true },
      { path: 'SKILL_UNIT_EVALS.md', purpose: 'per-skill sandbox regression test design', required: true },
      { path: 'ACTIVATION_EVALS.md', purpose: 'component trigger, routing, positive/negative prompt evals', required: true },
      { path: 'TRANSCRIPT_PROCESS_EVALS.md', purpose: 'order-of-operations and workflow compliance checks', required: true },
      { path: 'E2E_TASK_BENCH.md', purpose: 'complete repo-task benchmark classes and scoring', required: true },
      { path: 'MULTI_AGENT_SAFETY.md', purpose: 'subagent context, output schema, file ownership, and worktree safety', required: true },
      { path: 'SAFETY_POLICY.md', purpose: 'hard-fail policy for secrets, external actions, permissions, and fabricated evidence', required: true },
      { path: 'SCORECARD.md', purpose: 'weighted scoring model and status bands', required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'VALIDATION_REPORT.md', purpose: 'proof and package validation status', required: true },
      { path: 'proof/package.json', purpose: 'offline proof scripts', required: false },
      { path: 'proof/package-lock.json', purpose: 'offline proof lockfile', required: false },
      { path: 'proof/src/eval-os.mjs', purpose: 'deterministic evaluation pipeline/scoring proof', required: false },
      { path: 'proof/test/eval-os.test.mjs', purpose: 'offline proof tests for snapshot/lint/loadout/skill/activation/transcript/multi-agent scoring', required: false },
    ],
    checks: ['Static-invalid setups fail before expensive behavior tests', 'Loadout inventory exposes loaded token tax and dormant artifacts', 'Skill unit tests are separated from activation tests', 'Activation evals include positive and negative prompts', 'Transcript checks enforce skill-before-action and approval-before-risky-action invariants', 'Multi-agent cases check parent context, output schema, and file ownership', 'Safety hard-fails override good final outputs', 'Offline proof passes 8/8 tests without live agents, providers, or network calls'],
    trustBadges: [
      { label: 'Deep stack design', detail: 'Combines skill-eval-runner, cc-plugin-eval, Superpowers-style transcripts, agnix, loadout inventory, and multi-agent safety layers.', tone: 'success' },
      { label: 'Offline proof passed', detail: 'Deterministic JavaScript proof validates snapshot, lint, loadout, activation, transcript, and multi-agent scoring.', tone: 'success' },
      { label: 'Not just skill tests', detail: 'Skill unit tests are one module; activation, process compliance, safety, and loadout cost are separate gates.', tone: 'info' },
      { label: 'Safety hard-fails', detail: 'Secrets, external writes, destructive actions, and fabricated evidence override aggregate scores.', tone: 'warning' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/complete-agent-skills-evaluation-os`,
    originGithubUrl: 'https://github.com/balyakin/skill-eval-runner',
    originLabel: 'balyakin/skill-eval-runner + eval stack',
    rawBaseUrl: rawFor('complete-agent-skills-evaluation-os'),
    copyPrompt: `${localPrompt('complete-agent-skills-evaluation-os', 'Complete Agent Skills Evaluation OS')} Build a complete evaluation stack for my coding-agent setup. Treat skill-eval-runner-style per-skill tests as one module only. Include setup snapshot, static lint, loadout/token inventory, activation/routing evals with positive and negative prompts, transcript/process checks, E2E task bench, multi-agent safety, safety hard-fails, and CI scorecard. Use offline fixtures by default; do not perform live external actions without approval.`,
  },


  {
    slug: 'portable-personal-agent-chat-os',
    title: 'Portable Personal Agent Chat OS',
    creator: 'Agent Buildprint',
    category: 'Mapped Project',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Any backend', 'TypeScript proof', 'Mock-first providers'],
    stack: ['Streaming chat', 'Provider router', 'Tools / Skills / MCP', 'Memory', 'Subagents', 'Telemetry'],
    iconKeys: ['typescript', 'json', 'md'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Clean-room, Emperor Agent-inspired personal agent chatbot OS with streaming chat, provider routing, tools, skills, MCP, memory, subagents, and token telemetry.',
    plainDescription: 'A blueprint for building a self-hosted personal AI assistant that behaves like a small chatbot operating system: chat UI, model router, tool dispatcher, skill registry, MCP adapter, memory, delegation, and usage telemetry.',
    whatYouGet: ['Personal agent chatbot OS architecture', 'Streaming runtime event contract', 'Provider router and fake-provider proof', 'Tool/skill/MCP policy boundaries', 'Three-tier memory and compaction model', 'Subagent/team delegation events', 'Token telemetry and head-to-foot QA'],
    whatYouNeed: ['Nothing for local deterministic proof mode', 'Provider keys only for optional live model adapters', 'A workspace/tool safety policy', 'Persistence choice for memory/history', 'MCP servers only if you want real external tools'],
    architectureFlow: ['Chat', 'Context + memory', 'Provider router', 'Tools / skills / MCP', 'Subagents', 'Telemetry'],
    promise: 'A validated mapped-project Buildprint for rebuilding a portable personal agent chatbot OS without copying Emperor Agent source or claiming exact clone/provider/tool parity.',
    includes: ['Clean-room source mapping', 'Streaming runtime contract', 'Provider router', 'Tool registry and safety policy', 'Skill registry', 'MCP adapter boundary', 'Memory/context compaction', 'Subagent/team bus', 'Token telemetry', 'Streaming WebUI map', 'Head-to-foot QA gate', 'Parity claims', 'Offline TypeScript proof'],
    risks: ['Overclaiming full Emperor Agent clone parity', 'Unsafe shell/filesystem/network tools', 'Provider API drift', 'Context truncation losing user instructions', 'Skill injection bloat', 'MCP timeout/security failures', 'Telemetry hidden from UI'],
    files: [
      { path: 'README.md', purpose: 'package overview and clean-room scope boundary', required: true },
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'AGENT_RUNTIME.md', purpose: 'evented agent loop, lifecycle, cancellation, and error model', required: true },
      { path: 'PROVIDER_ROUTER.md', purpose: 'multi-provider registry, capabilities, and usage normalization', required: true },
      { path: 'TOOL_SKILL_MCP.md', purpose: 'tool registry, skill registry, and MCP adapter policy', required: true },
      { path: 'MEMORY_CONTEXT.md', purpose: 'three-tier memory, context builder, and compaction rules', required: true },
      { path: 'STREAMING_WEBUI.md', purpose: 'WebUI views and runtime event transport expectations', required: true },
      { path: 'SUBAGENTS_TEAM.md', purpose: 'subagent/team task contract and event bus', required: true },
      { path: 'TOKEN_TELEMETRY.md', purpose: 'token usage counters, context pressure, and UI expectations', required: true },
      { path: 'SECURITY_POLICY.md', purpose: 'tool/MCP/secrets/sandbox safety policy', required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'HEAD_TO_FOOT_QA.md', purpose: 'canonical acceptance gate for generated agent OS proofs', required: true },
      { path: 'PARITY_CLAIMS.md', purpose: 'safe claims, unsafe claims, and upgrade evidence', required: true },
      { path: 'TRACEABILITY_MATRIX.md', purpose: 'source evidence to portable requirement mapping', required: true },
      { path: 'proof/package.json', purpose: 'offline proof scripts', required: false },
      { path: 'proof/package-lock.json', purpose: 'offline proof dependency lockfile', required: false },
      { path: 'proof/tsconfig.json', purpose: 'offline proof TypeScript config', required: false },
      { path: 'proof/src/index.ts', purpose: 'offline proof module exports', required: false },
      { path: 'proof/src/runtime.ts', purpose: 'deterministic personal agent runtime proof', required: false },
      { path: 'proof/test/runtime.test.ts', purpose: 'offline proof tests for streaming, tools, skills, MCP, memory, team, and telemetry', required: false },
      { path: 'proof/test/node-builtins.d.ts', purpose: 'offline proof local Node type shims', required: false },
    ],
    checks: ['Clean-room mapped-project scope; not a full Emperor Agent clone', 'Offline TypeScript proof builds without live providers or network calls', 'Proof streams deltas before completion', 'Tool policy denies shell by default', 'Skill selection and subagent delegation are traceable events', 'MCP fake tool maps through same ToolSpec boundary', 'Memory compacts under context pressure while retaining recent messages', 'Token telemetry is emitted and asserted'],
    trustBadges: [
      { label: 'Mapped from a real small OS chatbot', detail: 'Primary architecture source is TheSyart/emperor-agent, with JARVIS/ToFu used only as comparison pressure.', tone: 'success' },
      { label: 'Offline proof', detail: 'Deterministic TypeScript proof validates runtime contracts without live model, MCP, shell, or network calls.', tone: 'success' },
      { label: 'Safety-gated tools', detail: 'Shell/network/write risk is explicit; dangerous tools are denied unless policy allows them.', tone: 'info' },
      { label: 'Explicit parity boundary', detail: 'Claims stop at clean-room workflow/contract/mock-runtime proof unless upgraded with live evidence.', tone: 'warning' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/portable-personal-agent-chat-os`,
    originGithubUrl: 'https://github.com/TheSyart/emperor-agent',
    originLabel: 'TheSyart/emperor-agent',
    rawBaseUrl: rawFor('portable-personal-agent-chat-os'),
    copyPrompt: `${localPrompt('portable-personal-agent-chat-os', 'Portable Personal Agent Chat OS')} Build a clean-room personal agent chatbot OS with streaming chat, provider routing, tools, skills, MCP adapter, memory/compaction, subagent delegation, token telemetry, and safety-gated tool policy. Use fake providers/tools by default. Do not claim Emperor Agent clone, exact UI parity, live provider parity, shell parity, or real MCP parity unless separately validated.`,
  },

  {
    slug: 'perfect-rag-retrieval-os',
    title: 'Perfect RAG / Retrieval OS',
    creator: 'Agent Buildprint',
    category: 'Workflow OS',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['Any backend', 'TypeScript proof'],
    stack: ['Hybrid retrieval', 'Reranking', 'Citations', 'RAG evals'],
    iconKeys: ['typescript', 'json', 'md'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'Production-grade RAG blueprint with ingestion, chunking, hybrid retrieval, reranking, grounded citations, refusal behavior, permission filtering, and eval gates.',
    plainDescription: 'A stack-adaptable blueprint for building a serious RAG system: not just vector search, but measurable retrieval quality, reranking, grounded answers, and regression tests.',
    whatYouGet: ['Document ingestion and chunk contracts', 'Hybrid lexical/dense retrieval', 'Candidate fusion and dedupe', 'Reranker / late-interaction boundary', 'Citation-grounded answer generation', 'Refusal and permission-filter tests', 'Retrieval and answer-quality eval harness'],
    whatYouNeed: ['Nothing for local deterministic proof mode', 'Your document corpus and permission model', 'Search/vector infrastructure for production mode', 'Embedding/reranker/LLM provider keys only for live adapters', 'Eval cases that represent your real user questions'],
    architectureFlow: ['Documents', 'Chunks', 'Hybrid retrieve', 'Rerank', 'Grounded answer', 'Eval gates'],
    promise: 'An agent-grade workflow Buildprint for building benchmark-informed RAG systems with hybrid retrieval, reranking, citations, refusal behavior, tenant-safe retrieval, and measurable quality gates.',
    includes: ['Source and chunk contracts', 'Dense plus lexical/sparse retrieval architecture', 'Fusion and dedupe policy', 'Permission and tenant filters', 'Reranker adapter boundary', 'Grounded answer contract', 'RAG eval harness', 'Advanced technique guidance for HyDE, SPLADE, ColBERT, RAPTOR, GraphRAG, Self-RAG, and CRAG', 'Offline TypeScript proof'],
    risks: ['Vector-only false confidence', 'Hallucinated uncited answers', 'Permission leakage', 'Eval-free quality drift', 'Reranker latency/cost creep', 'Advanced-tech hype without measured gain'],
    files: [
      { path: 'README.md', purpose: 'package overview and research basis', required: true },
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'TARGET_STACK_ADAPTERS.md', purpose: 'portable mappings for Node, Python, Rails, Go, and Laravel stacks', required: true },
      { path: 'EVAL_HARNESS.md', purpose: 'retrieval, answer, and operational eval contract', required: true },
      { path: 'proof/package.json', purpose: 'offline proof scripts', required: false },
      { path: 'proof/package-lock.json', purpose: 'offline proof dependency lockfile', required: false },
      { path: 'proof/tsconfig.json', purpose: 'offline proof TypeScript config', required: false },
      { path: 'proof/src/index.ts', purpose: 'offline proof module exports', required: false },
      { path: 'proof/src/rag.ts', purpose: 'offline deterministic RAG pipeline proof', required: false },
      { path: 'proof/test/rag.test.ts', purpose: 'offline proof retrieval, answer, refusal, permission, and eval tests', required: false },
    ],
    checks: ['Research report validated with 18 sources and 16 evidence-backed claims', 'Offline TypeScript proof builds without network or provider keys', 'Proof compares lexical, dense-like, hybrid, and reranked retrieval paths', 'Grounded answer includes citations from selected chunks', 'Unsupported query refuses with insufficient-evidence', 'Tenant/private retrieval filter blocks unauthorized chunks', 'Eval harness emits machine-readable recall@5 and MRR-style metrics'],
    trustBadges: [
      { label: 'Benchmark-informed', detail: 'Research cross-checked BEIR, MTEB, ColBERT, SPLADE, HyDE, RAPTOR, Self-RAG, CRAG, GraphRAG, Ragas, and retrieval-eval docs.', tone: 'success' },
      { label: 'Hybrid + rerank by default', detail: 'Blueprint avoids vector-only RAG and makes reranking/eval gates first-class.', tone: 'success' },
      { label: 'Offline proof', detail: 'Deterministic TypeScript proof runs without live model, vector DB, or provider credentials.', tone: 'info' },
      { label: 'Permission-safe retrieval', detail: 'Tenant/private filters are part of the proof and acceptance tests.', tone: 'success' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/perfect-rag-retrieval-os`,
    rawBaseUrl: rawFor('perfect-rag-retrieval-os'),
    copyPrompt: `${localPrompt('perfect-rag-retrieval-os', 'Perfect RAG / Retrieval OS')} First identify my corpus, permissions, backend stack, search/vector infrastructure, latency/cost budget, and eval cases. Implement ingestion, chunking, hybrid retrieval, fusion/dedupe, permission filtering, reranking, grounded cited answers, refusal behavior, trace logging, and retrieval/answer evals. Use deterministic mocks in tests; do not call live model/vector/reranker providers unless explicitly configured.`,
  },
  {
    slug: 'stripe-billing-extension',
    title: 'Stripe Billing Extension',
    creator: 'Agent Buildprint',
    category: 'Feature / Extension',
    tier: 'basic',
    status: 'validated',
    runtime: ['Any backend', 'TypeScript proof'],
    stack: ['Stripe', 'Webhooks', 'Entitlements', 'SaaS'], 
    iconKeys: ['typescript', 'stripe', 'json'],
    difficulty: 'Medium',
    featured: true,
    summary: 'Add SaaS billing to any backend without forgetting checkout, subscriptions, trials, portal, webhooks, entitlement checks, and billing UI.',
    plainDescription: 'A portable blueprint for adding paid SaaS billing to an existing backend: checkout, subscriptions, customer portal, webhooks, entitlement checks, and billing settings.',
    whatYouGet: ['Stripe checkout flow', 'Subscription and trial handling', 'Customer portal entry point', 'Verified webhook handler', 'Server-side entitlement checks', 'Billing settings UI'],
    whatYouNeed: ['Stripe account and API keys for live billing', 'Webhook signing secret for production webhooks', 'Product/pricing decisions from the human', 'Nothing for mocked/local billing tests'],
    architectureFlow: ['Checkout', 'Webhook', 'Subscription', 'Entitlements', 'Portal', 'Billing UI'],
    promise: 'A practical extension Buildprint for the paid-app foundation coding agents often implement incompletely.',
    includes: ['Checkout session', 'Subscriptions and trials', 'Customer portal', 'Webhook handler', 'Subscription state model', 'Entitlement guards', 'Billing settings UI'],
    risks: ['Webhook signature skipped', 'Frontend state trusted for access', 'Failed payment states ignored', 'Portal exposed without auth', 'Subscription state drift'],
    files: [
      { path: 'README.md', purpose: 'package overview and validation summary', required: true },
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'TARGET_STACK_ADAPTERS.md', purpose: 'portable backend mappings for Node, Python, Rails, Go, and PHP/Laravel', required: true },
      { path: 'proof/package.json', purpose: 'dry-run proof package scripts', required: false },
      { path: 'proof/tsconfig.json', purpose: 'dry-run proof TypeScript config', required: false },
      { path: 'proof/src/index.ts', purpose: 'dry-run proof module exports', required: false },
      { path: 'proof/src/billing/types.ts', purpose: 'dry-run proof billing types', required: false },
      { path: 'proof/src/billing/env.ts', purpose: 'dry-run proof env var name list', required: false },
      { path: 'proof/src/billing/errors.ts', purpose: 'dry-run proof billing errors', required: false },
      { path: 'proof/src/billing/store.ts', purpose: 'dry-run proof in-memory subscription store', required: false },
      { path: 'proof/src/billing/provider.ts', purpose: 'dry-run proof mocked billing provider', required: false },
      { path: 'proof/src/billing/service.ts', purpose: 'dry-run proof checkout and portal service', required: false },
      { path: 'proof/src/billing/webhookVerifier.ts', purpose: 'dry-run proof mockable signature verifier', required: false },
      { path: 'proof/src/billing/webhook.ts', purpose: 'dry-run proof webhook lifecycle handler', required: false },
      { path: 'proof/src/billing/entitlements.ts', purpose: 'dry-run proof server-side entitlement guard', required: false },
      { path: 'proof/src/ui/billingUi.ts', purpose: 'dry-run proof billing settings UI stub', required: false },
      { path: 'proof/test/billing.test.ts', purpose: 'dry-run proof lifecycle tests', required: false },
      { path: 'proof/test/node-builtins.d.ts', purpose: 'dry-run proof local Node type shims', required: false },
    ],
    checks: ['Codex dry-run generated a TypeScript billing proof', 'npm run build passed in dry-run proof', 'npm test passed: 6/6 lifecycle tests', 'Target-stack adapters document Node/TypeScript, Python, Rails, Go, and PHP/Laravel mappings', 'Webhook signatures verified before state mutation', 'Premium access uses server-side subscription state', 'Portal requires authenticated customer', 'Failed/canceled/trialing states handled'],
    trustBadges: [
      { label: 'Codex dry-run passed', detail: 'Fresh Codex run built an offline TypeScript billing proof from the Buildprint package.', tone: 'success' },
      { label: '6/6 tests passed', detail: 'Checkout, portal, webhook signature, lifecycle states, entitlements, and billing UI stub are covered.', tone: 'success' },
      { label: 'Portable backend contract', detail: 'Adapters preserve the same checkout, webhook, state, entitlement, portal, and test boundaries across stacks.', tone: 'info' },
      { label: 'No real Stripe calls', detail: 'Validation uses mock providers and env var names only; no secrets or network billing calls.', tone: 'info' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/stripe-billing-extension`,
    rawBaseUrl: rawFor('stripe-billing-extension'),
    copyPrompt: `${localPrompt('stripe-billing-extension', 'Stripe Billing Extension')} First identify my backend stack, routing/auth/database/test patterns, then adapt TARGET_STACK_ADAPTERS.md to that stack. Implement billing with verified webhooks, server-side subscription state, entitlements, customer portal, billing UI, and lifecycle tests. Use env var names only; do not call real Stripe APIs in tests.`, 
  },
  {
    slug: 'portable-ai-shorts-production-studio',
    title: 'Portable AI Shorts Production Studio',
    creator: 'Agent Buildprint',
    category: 'Mapped Project',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['JavaScript', 'Clean-room web proof'],
    stack: ['Product analysis', 'UGC scripts', 'Actor / voice adapters', 'Video composition', 'Gallery SEO'],
    iconKeys: ['typescript', 'json', 'md'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'OpenShorts-inspired AI shorts production Buildprint with product analysis, UGC script generation, actor/voice provider adapters, mocked media jobs, 9:16 composition, gallery SEO, and social handoff.',
    plainDescription: 'A blueprint for an AI shorts production studio: start from a product, generate a UGC script, choose actor/voice options, queue media jobs, plan a 9:16 video, and hand off gallery/social assets.',
    whatYouGet: ['AI shorts production studio', 'Product input and product analysis flow', 'UGC script generator', 'Actor/avatar and voice selection flow', 'Mock talking-head, b-roll, and subtitle job pipeline', '9:16 composition plus gallery/SEO/social handoff'],
    whatYouNeed: ['Nothing for local/mock proof mode', 'AI provider key for real product analysis and script generation', 'TTS provider key for real voiceover', 'Image/video provider keys for live media generation', 'Storage or social credentials only if you want real publishing'],
    architectureFlow: ['Product', 'Script', 'Voice/avatar', 'Media jobs', '9:16 video', 'Gallery/social'],
    promise: 'A validated mapped-project Buildprint for rebuilding a portable AI shorts production pipeline from public OpenShorts architecture patterns without claiming OpenShorts clone, provider/API, rendering-quality, or social-platform parity.',
    includes: ['Pinned OpenShorts source trace', 'Repo facts and fork/license boundary notes', 'Product URL/manual-input analysis flow', 'Five-segment UGC script contract', 'Actor gallery/generated/uploaded selection model', 'Voiceover adapter contract', 'Talking-head/lipsync adapter contract', 'B-roll generation adapter contract', 'Subtitle and hook overlay composition plan', '9:16 video manifest', 'Gallery SEO VideoObject manifest', 'Social publishing handoff manifest', 'Threat model for keys, likeness, scraping, and gallery exposure', 'Clean-room runnable proof with tests'],
    risks: ['Accidentally implying OpenShorts clone parity', 'Provider/API parity overclaiming', 'Video quality/rendering parity overclaiming', 'Social platform publishing reliability overclaiming', 'User likeness/copyright/consent under-specification', 'Client-side API key handling scope creep'],
    files: [
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'TRACEABILITY_MATRIX.md', purpose: 'source evidence to requirement/check traceability', required: true },
      { path: 'PARITY_CLAIMS.md', purpose: 'safe claims, prohibited claims, and explicit non-goals', required: true },
      { path: 'QA_PLAN.md', purpose: 'validation and reversal proof plan', required: true },
      { path: 'THREAT_MODEL.md', purpose: 'key/likeness/scraping/provider/gallery safety model', required: true },
      { path: 'SOURCE_TRACE.md', purpose: 'OpenShorts source evidence grouped by capability', required: true },
      { path: 'SYSTEM_MAP.md', purpose: 'OpenShorts system map and pipeline layers', required: true },
    ],
    checks: ['Mapped source commit is recorded: fe87af6dd599b854e6eab2de0ca247ebafe13885', 'Required Mapper OS artifacts exist', 'Source trace cites concrete OpenShorts files/line ranges', 'Clean-room proof is built from Buildprint docs, not OpenShorts imports', 'npm run check passes in clean-room proof', '7/7 proof tests pass', 'Claim boundary remains workflow-proof + contract-parity + mocked-provider proof', 'Full clone/provider/API/rendering/social-platform parity are explicitly out of scope'],
    trustBadges: [
      { label: 'Runnable proof passed', detail: 'Clean-room JavaScript proof passes 7/7 tests and builds dist/.', tone: 'success' },
      { label: 'Visual product pipeline', detail: 'Maps product analysis through script, actor, voice, media jobs, composition, gallery, and publishing handoff.', tone: 'info' },
      { label: 'OpenShorts-inspired, not clone', detail: 'Public boundary excludes clone, provider/API, rendering-quality, and social-platform parity.', tone: 'warning' },
      { label: 'Mocked providers', detail: 'External video, voice, storage, and social services are modeled as adapters/mocks.', tone: 'neutral' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/portable-ai-shorts-production-studio`,
    originGithubUrl: 'https://github.com/mutonby/openshorts',
    originLabel: 'mutonby/openshorts',
    rawBaseUrl: rawFor('portable-ai-shorts-production-studio'),
    copyPrompt: `${localPrompt('portable-ai-shorts-production-studio', 'Portable AI Shorts Production Studio')} Build a clean-room AI shorts production proof from the Buildprint package. Keep claims scoped to workflow-proof + contract-parity + mocked-provider proof. Do not call it an OpenShorts clone, drop-in replacement, provider/API parity implementation, rendering-quality parity proof, or social-platform publishing parity proof.`,
  },
  {
    slug: 'portable-durable-agent-graph-runtime',
    title: 'Portable Durable Agent Graph Runtime',
    creator: 'Agent Buildprint',
    category: 'Mapped Project',
    tier: 'agent-grade',
    status: 'validated',
    runtime: ['TypeScript', 'Clean-room runtime proof'],
    stack: ['Typed state graph', 'Reducers', 'Checkpointing', 'Interrupt/resume', 'Send fanout'],
    iconKeys: ['typescript', 'json', 'md'],
    difficulty: 'Advanced',
    featured: true,
    summary: 'LangGraph-inspired durable graph runtime Buildprint with source trace, scoped TypeScript reversal proof, checkpoints, interrupts, streaming, reducers, and Send fanout.',
    plainDescription: 'A blueprint for a durable agent graph runtime: define graph nodes, route state through edges, checkpoint progress, resume interrupted runs, and stream execution events.',
    whatYouGet: ['Durable agent graph runtime', 'Graph builder API', 'State schema and reducer model', 'Conditional routing and fanout', 'Checkpoint/resume behavior', 'Interrupt/recovery and stream events'],
    whatYouNeed: ['Nothing for local/mock runtime proof', 'Database/storage credentials only if replacing the in-memory checkpoint saver', 'AI/model/tool provider keys only if your nodes call real external services'],
    architectureFlow: ['Graph builder', 'State', 'Routing', 'Checkpoint', 'Interrupt', 'Stream'],
    promise: 'A validated mapped-project Buildprint for rebuilding a small portable durable graph runtime from evidence-backed LangGraph architecture concepts without claiming clone, drop-in, API, provider, cloud, storage, or Pregel parity.',
    includes: ['Pinned LangGraph source trace', 'Builder / compile / runtime architecture map', 'Typed-ish state schema and reducers', 'Directed and conditional routing', 'Invoke/stream contracts', 'Checkpoint tuple and in-memory saver contract', 'Pending-write recovery simulation', 'Interrupt/resume via Command', 'Send fanout proof', 'Async invoke/stream proof', 'Serializer safety gate', 'Clean-room TypeScript reversal proof', 'QA and reversal reports'],
    risks: ['Accidentally implying LangGraph clone parity', 'API compatibility overclaiming', 'Pregel concurrency/performance overclaiming', 'Provider/tool ecosystem scope creep', 'Production storage adapter overclaiming', 'Serializer/checkpoint byte compatibility overclaiming'],
    files: [
      { path: 'README.md', purpose: 'package overview and clean-room boundary', required: true },
      { path: 'BUILDPRINT.md', purpose: canonicalFilePurposes['BUILDPRINT.md'], required: true },
      { path: 'SPEC.md', purpose: canonicalFilePurposes['SPEC.md'], required: true },
      { path: 'PLAN.md', purpose: canonicalFilePurposes['PLAN.md'], required: true },
      { path: 'CONTRACTS.md', purpose: canonicalFilePurposes['CONTRACTS.md'], required: true },
      { path: 'TEST_MATRIX.md', purpose: canonicalFilePurposes['TEST_MATRIX.md'], required: true },
      { path: 'TRACEABILITY_MATRIX.md', purpose: 'source evidence to requirement/check traceability', required: true },
      { path: 'PARITY_CLAIMS.md', purpose: 'safe claims, prohibited claims, and explicit non-goals', required: true },
      { path: 'QA_PLAN.md', purpose: 'validation and reversal proof plan', required: true },
      { path: 'THREAT_MODEL.md', purpose: 'serializer/checkpoint/node-output safety model', required: true },
      { path: 'SOURCE_TRACE.md', purpose: 'pinned LangGraph source trace with OBSERVED evidence', required: true },
      { path: 'SYSTEM_MAP.md', purpose: 'selected system map and runtime layers', required: true },
    ],
    checks: ['Pinned source commit is recorded: 076e2a3627206f5a1aef573aaca4a01e5af897ca', '166 source references checked with 0 missing and 0 bad line ranges', 'Clean-room TypeScript proof uses Buildprint docs only, not LangGraph source imports', 'npm test runs tsc and node --test', '12/12 proof tests pass', 'Claim boundary remains workflow-proof + contract-parity + mocked-runtime-proof', 'Full clone/API/provider/cloud/storage/Pregel parity are explicitly out of scope'],
    trustBadges: [
      { label: 'Scoped reversal proof passed', detail: 'Clean-room TypeScript proof passes 12/12 tests from the Buildprint package.', tone: 'success' },
      { label: 'Evidence trace checked', detail: '166 pinned-source references checked with 0 missing files and 0 bad ranges.', tone: 'success' },
      { label: 'LangGraph-inspired, not clone', detail: 'Public claim boundary excludes clone, API, cloud/provider, storage, and Pregel parity.', tone: 'warning' },
      { label: 'TypeScript proof', detail: 'Includes tsc build, public declarations, async surfaces, Send fanout, and pending-write recovery simulation.', tone: 'info' },
    ],
    githubUrl: `${repoUrl}/tree/main/buildprints/portable-durable-agent-graph-runtime`,
    originGithubUrl: 'https://github.com/langchain-ai/langgraph',
    originLabel: 'langchain-ai/langgraph',
    rawBaseUrl: rawFor('portable-durable-agent-graph-runtime'),
    copyPrompt: `${localPrompt('portable-durable-agent-graph-runtime', 'Portable Durable Agent Graph Runtime')} Build a clean-room TypeScript durable graph runtime proof from the Buildprint package. Keep claims scoped to workflow-proof + contract-parity + mocked-runtime-proof. Do not call it a LangGraph clone, drop-in replacement, full API-compatible runtime, LangSmith/cloud equivalent, provider/tool parity implementation, production storage adapter, or Pregel concurrency/performance parity.`,
  },
];

export const categories = ['All', 'Framework / Architecture', 'Product OS', 'Feature / Extension', 'Workflow OS', 'Mapped Project'] as const;
export const tiers = ['All', 'basic', 'strong', 'agent-grade'] as const;
export const getBuildprint = (slug: string) => buildprints.find((item) => item.slug === slug);
export const liveBuildprints = buildprints;

export function buildprintUrls(bp: Buildprint) {
  return { human: `/buildprints/${bp.slug}/`, agent: `/buildprints/${bp.slug}/agent.md`, manifest: `/buildprints/${bp.slug}/package.json`, prompt: `/buildprints/${bp.slug}/prompt.txt`, files: bp.rawBaseUrl };
}

export function packageManifest(bp: Buildprint) {
  const urls = buildprintUrls(bp);
  return {
    schema: `${siteBase}/schemas/buildprint-package.v1.json`,
    slug: bp.slug,
    title: bp.title,
    category: bp.category,
    tier: bp.tier,
    status: bp.status,
    runtime: bp.runtime,
    stack: bp.stack,
    entrypoints: { human: urls.human, agent: urls.agent, manifest: urls.manifest, prompt: urls.prompt, github: bp.githubUrl, originGithub: bp.originGithubUrl, rawBase: bp.rawBaseUrl },
    bootstrap: {
      command: `agb start ${siteBase}/buildprints/${bp.slug}/package.json`,
      fallbackCommand: `git clone https://github.com/DomEscobar/agent-buildprint && node agent-buildprint/bin/agb.js start ${siteBase}/buildprints/${bp.slug}/package.json`,
      stateDir: '.buildprint',
      snapshotMode: 'download_exact',
      rule: 'Do not write, summarize, or regenerate snapshot files manually. Use agb start to download exact files from this manifest.'
    },
    files: bp.files.map((file) => ({ ...file, rawUrl: `${bp.rawBaseUrl}/${file.path}` })),
    instructions: {
      canonicalStart: 'BUILDPRINT.md',
      readOrder: ['BUILDPRINT.md'].filter((path) => bp.files.some((file) => file.path === path)),
      rule: 'Do not scrape human cards. Use this manifest, agent.md, and raw files. BUILDPRINT.md is the canonical start file and owns the required read order, phase gates, and acceptance gates. Structured control files are machine-readable mirrors only.',
    },
  };
}
